# Run in container-based environment
sudo: required

# Using the precompiled toolchain from docker
services:
  - docker

before_install:
 - docker pull lowrisc/lowrisc-docker:untether-v0.2

before_script:
 - docker create -v $PWD:/opt/lowrisc -e TOP=/opt/lowrisc -t --name=test lowrisc/lowrisc-docker:untether-v0.2
 - docker start test

script:
 - docker exec test /bin/bash -c "make -C \$TOP/vsim run-asm-tests"

after_script:
 - docker stop test
 - docker rm test