# Run in container-based environment
sudo: required
dist: trusty

# Install the build requirements
addons:
  apt:
   packages:
    # Dependencies from tutorial
    - autoconf
    - automake
    - autotools-dev
    - curl
    - libmpc-dev
    - libmpfr-dev
    - libgmp-dev
    - gawk
    - build-essential
    - bison
    - flex
    - texinfo
    - gperf
    - libncurses5-dev
    - libusb-1.0-0
    - libboost-dev

# Environment
env:
 global:
  - VERILATOR_ROOT=$HOME/tools/verilator
  - PATH=$VERILATOR_ROOT/bin:$PATH
  - JOBS=4

before_install:
 - git submodule update --init --recursive

# Execute the build
install:
 - source set_riscv_env.sh
 # Build verilator
 - mkdir -p $HOME/tools
 - cd $HOME/tools
 - git clone http://git.veripool.org/git/verilator
 - cd verilator
 - autoconf
 - ./configure > /dev/null
 - make -j $JOBS > /dev/null
 # Build RISC-V cross-compilation tools
 - cd $TOP/riscv-tools
 - sed -i 's/JOBS=16/JOBS=$JOBS/' build.common
 - ./build.sh

script:
 # Build RTL simulation
 - cd $TOP/vsim
 - make sim
 # Build RTL simulation with vcd
 - cd $TOP/vsim
 - make sim-debug
 # Run asm tests
 # Add . to PATH so that make finds it (will be changed)
 - export PATH=.:$PATH
 - make run-asm-tests
